
# refresca la autenticación.
# @name login
POST {{host}}/{{version}}/refresh-token/
Content-Type: application/json
User-Agent: {{userAgent}}

{
    "refresh":"{{refreshToken}}"
}

### ENLISTA RESUMES DE USUARIO AUTENTICADO

GET {{host}}/{{version}}/resumes/
Content-Type: application/json
User-Agent: {{userAgent}}
Authorization: Bearer {{login.response.body.access}}

### CREAR UN RESUME

POST  {{host}}/{{version}}/resumes/
Content-Type: application/json
User-Agent: {{userAgent}}
Authorization: Bearer {{login.response.body.access}}

{
  "id": 1,
  "skills": [
    {
      "name": "Web Development",
      "level": "Master",
      "keywords": [
        "HTML",
        "CSS",
        "JavaScript"
      ],
      "orden": 0
    },
    {
      "name": "Web Development 3",
      "level": "Master",
      "keywords": [
        "HTML",
        "CSS",
        "JavaScript"
      ],
      "orden": 1
    }
  ],
  "experiences": [
    {
      "name": "Desarrollador Web, Malambo Atlántico",
      "position": "President",
      "url": "https://company.com",
      "highlights": [],
      "summary": "Fui parte del Desarrollo de la web usando Djando del lado del backend y para la interactividad de la web usando JavaScript con JQuery.",
      "start_date": "2025-01-10",
      "end_date": "2025-01-10",
      "orden": 1
    }
  ],
  "full_name": "Leonardo {{$guid}}",
  "email": "leocasti{{$guid}}@gmail.com",
  "created_at": "2024-12-11T17:27:20.679337Z",
  "updated_at": "2025-01-26T11:21:08.062048Z",
  "summary": "Soy un apasionado del desarrollo web y actualmente estoy estudiando un curso de desarrollador web en Alura Latam. Formé parte del desarrollo de una aplicación web usando Django para",
  "template_selected": 2
}


