
# LOGIN NECESARIO PARA USAR LOS REQUEST
# @name login
POST {{host}}/{{version}}/login/
Content-Type: application/json
User-Agent: {{userAgent}}

{
    "username": "admin",
    "password": "admin"
}

###
### ENLISTA TODOS LOS TEMPLATES DISPONIBLES
GET {{host}}/{{version}}/templates/
Content-Type: application/json
User-Agent: {{userAgent}}
Authorization: Bearer {{login.response.body.access}}


###
### OBTENER LOS DETALLES DE UN TEMPLATE
GET {{host}}/{{version}}/templates/2/
Content-Type: application/json
User-Agent: {{userAgent}}
Authorization: Bearer {{login.response.body.access}}


###
### CREAR UN TEMPLATE
POST  {{host}}/{{version}}/templates/
Content-Type: application/json
User-Agent: {{userAgent}}
Authorization: Bearer {{login.response.body.access}}

{
  "name": "template nuevo",
  "descripcion": "El siguiente template es un nuevo estilo moderno",
  "componet_name": "component-moderno",
  "customization_rules": {"color":["yellow", "black", "white"],"margins":{"min":1,"max":24}, "font_size":{"min":1,"max":24}}
}

###
### ACTUALIZA PARTIAL UN TEMPLATE
# solo actualiza los campos enviados
PATCH  {{host}}/{{version}}/templates/2/
Content-Type: application/json
User-Agent: {{userAgent}}
Authorization: Bearer {{login.response.body.access}}

{
  "name": "template nuevo",
  "descripcion": "El siguiente template es un nuevo estilo moderno",
  "componet_name": "component-moderno",
  "customization_rules": {"color":["yellow", "black", "white"],"margins":{"min":1,"max":24}, "font_size":{"min":1,"max":24}}
}

###
### ACTUALIZACIÓN DE REEMPLAZO DE UN TEMPLATE
PUT  {{host}}/{{version}}/templates/2/
Content-Type: application/json
User-Agent: {{userAgent}}
Authorization: Bearer {{login.response.body.access}}

{
  "name": "template nuevo",
  "componet_name": "component-moderno",
  "customization_rules": {"color":["yellow", "black", "white"],"margins":{"min":1,"max":24}, "font_size":{"min":1,"max":24}}
}


###
### ELIMINA UN TEMPLATE
DELETE  {{host}}/{{version}}/templates/16/
Content-Type: application/json
User-Agent: {{userAgent}}
Authorization: Bearer {{login.response.body.access}}

# TODO: ¿Que le ocurre si se elimina un template que este en uso?