# Generated by Django 5.1.4 on 2024-12-11 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Company Name', max_length=100)),
                ('position', models.CharField(default='President', max_length=100)),
                ('url', models.URLField(default='https://company.com')),
                ('highlights', models.JSONField(default=['Empezó la empresa'])),
                ('summary', models.TextField(default='Description…')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_app.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Web Development', max_length=100)),
                ('level', models.CharField(default='Master', max_length=100)),
                ('keywords', models.JSONField(default=['HTML', 'CSS', 'JavaScript'])),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_app.resume')),
            ],
        ),
    ]
