# Generated by Django 5.1.4 on 2024-12-11 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0002_alter_experience_highlights_alter_experience_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='resume',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template', to='resume_app.resume'),
        ),
    ]
