# Generated by Django 5.1.4 on 2024-12-12 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0004_rename_html_structure_template_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_styles', models.JSONField(default=list)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_app.resume')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_app.template')),
            ],
        ),
    ]
