# Generated by Django 5.1.4 on 2025-01-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0005_resumecustomization'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='orden',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
