# Generated by Django 5.1.4 on 2025-01-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0007_alter_experience_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='orden',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
