# Generated by Django 5.1.4 on 2025-01-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0008_skill_orden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['orden']},
        ),
        migrations.RemoveConstraint(
            model_name='experience',
            name='unique_order_per_resume',
        ),
        migrations.AddConstraint(
            model_name='experience',
            constraint=models.UniqueConstraint(fields=('resume', 'orden'), name='unique_order_per_resume_experience'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('resume', 'orden'), name='unique_order_per_resume_skill'),
        ),
    ]
