# Generated by Django 5.1.4 on 2025-01-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0010_experience_created_at_experience_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='resumecustomization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='resumetemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
