# Generated by Django 5.1.4 on 2025-02-07 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0013_usersession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
