# Generated by Django 5.1.4 on 2025-02-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0014_delete_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='highlights',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='url',
            field=models.URLField(default='https://company.com', null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='keywords',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(default='Master', max_length=100, null=True),
        ),
    ]
