# Generated by Django 5.1.4 on 2025-02-09 16:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0015_alter_experience_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='summary',
            field=models.TextField(default='Description…', null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
