# Generated by Django 5.1.4 on 2025-02-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0017_alter_experience_options_alter_resume_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='highlights',
            field=models.JSONField(default=list, help_text='Lista de Aspectos destacados del trabajo.', null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='url',
            field=models.URLField(default='https://company.com', help_text='Enlace a la empresa', null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='summary',
            field=models.TextField(help_text='Resumen o descripción general del usuario.', max_length=500, null=True),
        ),
    ]
