# Generated by Django 5.1.4 on 2025-02-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0018_alter_experience_highlights_alter_experience_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='summary',
            field=models.TextField(default='Description…', help_text='Descripción general de la experiencia laboral.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='url',
            field=models.URLField(default='https://company.com', help_text='Enlace a la empresa', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='descripcion',
            field=models.TextField(help_text='Descripción de la plantilla.', max_length=500, null=True),
        ),
    ]
