# Generated by Django 5.1.4 on 2025-02-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0020_alter_experience_highlights_alter_skill_keywords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['order'], 'verbose_name': 'Experiencia', 'verbose_name_plural': 'Experiencias'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order'], 'verbose_name': 'Habilidad', 'verbose_name_plural': 'Habilidades'},
        ),
        migrations.RemoveConstraint(
            model_name='experience',
            name='unique_order_per_resume_experience',
        ),
        migrations.RemoveConstraint(
            model_name='skill',
            name='unique_order_per_resume_skill',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='orden',
        ),
        migrations.AddField(
            model_name='experience',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='order en el que se mostrarán las experiencias en el resumen.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='order en el que se mostrarán las habilidades en el resumen.'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='experience',
            constraint=models.UniqueConstraint(fields=('resume', 'order'), name='unique_order_per_resume_experience'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('resume', 'order'), name='unique_order_per_resume_skill'),
        ),
    ]
