# Generated by Django 5.1.4 on 2025-02-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0021_alter_experience_options_alter_skill_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='resumecustomization',
            constraint=models.UniqueConstraint(fields=('resume', 'template'), name='unique_resume_template_customization'),
        ),
    ]
