# Generated by Django 5.1.4 on 2025-03-14 02:56

import resume_app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0025_alter_resumecustomization_custom_styles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='componet_name',
            field=models.CharField(help_text='Nombre del componente web asociado a la plantilla.', max_length=100, validators=[resume_app.utils.is_valid_webcomponent]),
        ),
    ]
